config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'products#index'

  resources :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_product, only: [:show, :destroy]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params.merge(user_id: current_user.id))
    redirect_to @product
  end

  def show
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description)
  end

  def get_product
    @product = Product.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AdminstrateDemo</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="row">
      <div class="col-sm-3 col-sm-offset-9">
        <% if user_signed_in? %>
          <%= current_user.email %>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        <% else %>
          <%= link_to('Login', new_user_session_path)  %>
          <%= link_to('Register', new_user_registration_path)  %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-4 col-sm-offset-4">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for :product do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Go to index", products_path %>

app/views/products/index.html.erb
<h1> List of products: </h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>User</th>
    <th></th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td>
        <%= product.name %>
      </td>
      <td>
        <%= product.description %>
      </td>
      <td>
        <%= product.user.email %>
      </td>
      <td>
        <%= link_to "View", product %>
      </td>
    </tr>
  <% end %>
</table>


<%= link_to "New product", new_product_path, :class => "btn btn-default" %>

app/views/products/new.html.erb
<%= form_for :product, url: products_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit "Save product", :class => "btn btn-default" %>
  </p>
<% end %>

<%= link_to "Go to index", products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user.email %>
</p>

<%= link_to "Destroy product", @product, method: :delete, :class => "btn btn-default" %>


<%= link_to "Go to index", products_path %>